# Site settings
title: Open Source Paper Review
email: Bravish.Ghosh@outlook.com
description: Explore the domain of research and development along with us in the field of Science and Technology
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Bravish_Ghosh
github_username: LoopGlitch26
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/OSPR-SS/OSPR-SS.github.io/blob/main/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/OSPR-SS/OSPR-SS.github.io/new/main
#########################################
disqus_shortname: ospr-ss
disqus_url: "https://ospr-ss.github.io/"
#########################################

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
